### ISSUE TITLE
OT color transfer in LAB space?

### ISSUE THREAD

**Issue by iperov** [dcoeurjo/OTColorTransfer#1]
did you try?

**Comment by iperov** [comment]
done https://github.com/dcoeurjo/OTColorTransfer/issues/2

**Comment by dcoeurjo** [comment]
👌
Yes I did try for many colorspaces that have relevant embedding to the unit cube (with the Euclidean metric). As you have shown in your code, results can be different but it is sometimes hard to decide which one is best (and for pedagogical considerations, I kept the RGB space in the doc.
