### ISSUE TITLE
References and Test Interfaces

### ISSUE THREAD

**Issue by notknowchild** [dcoeurjo/OTColorTransfer#4]
Hello, what is the main reference for this project? I want to learn it theoretically. I saw that you recently added python code. I tried to test but it failed. Can you add some test interfaces for some beginners to learn? Thank you.

**Comment by dcoeurjo** [comment]
Please have a look to the main website for this project: https://dcoeurjo.github.io/OTColorTransfer/ 
You'll find all references and basic instructions.
