### ISSUE TITLE
CMakeList git conflict merged

### ISSUE THREAD

**Issue by edmBernard** [dcoeurjo/OTColorTransfer#5]
Hi,
I saw there is uncorrected git conflict pushed in CMakeList :
 
    <<<<<<< HEAD
    cmake_minimum_required(VERSION 3.12)
    =======
    cmake_minimum_required(VERSION 3.9)
    >>>>>>> 8e4646fa93495df73f7bf4fdd394e6f838ed0bba

**Comment by dcoeurjo** [comment]
oops.. no idea what happened. Thanks a lot for the bug report, should be ok now.
